alias: Attic door closed
trigger:
  platform: state
  entity_id: binary_sensor.play_room_attic_door
  to: 'off'
action:
  - service: html5.dismiss
    data:
      data:
        tag: attic-door-notification
  - delay:
      minutes: 5
  - service: homeassistant.turn_off
    entity_id:
      - group.east_attic_lights
