alias: Attic door open
trigger:
  platform: state
  entity_id: binary_sensor.play_room_attic_door
  to: 'on'
action:
  - service: homeassistant.turn_on
    entity_id:
      - group.east_attic_lights
  - service: notify.webapp
    data:
      title: Attic door
      message:
        Attic door is open, you should go close it. Be sure to check for the
        Kit.
      data:
        tag: attic-door-notification
