homeassistant:
  name: Feliciterra
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml

zone: !include zones.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage

config:

cloud:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

mobile_app:

# Used to support RTSP video feeds
stream:

system_health:

system_log:

logger:
  default: warn
  # logs:
  #   custom_components.hacs: debug

hassio:

discovery:

recorder:
  db_url: !secret database_url
  purge_keep_days: 60

history:

logbook:

sun:

sensor: !include_dir_list sensors

binary_sensor: !include_dir_list binary_sensors

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 300

media_source:

media_player: !include media_players.yaml

# camera:
#   - platform: generic
#     name: WKRG
#     still_image_url: http://10.0.0.23:5004/auto/v3.1
#     stream_source: http://10.0.0.23:5004/auto/v3.1

notify:
  - name: webapp
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

alert: !include_dir_named alerts

scene: !include scenes.yaml

#automation manual: !include_dir_list automations
automation ui: !include automations.yaml

input_boolean: !include input_booleans.yaml

envisalink: !include envisalink.yaml

rest_command: !include_dir_named rest_commands

map:
