homeassistant:
  name: Feliciterra
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml

zone: !include zones.yaml

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: yaml

config:

cloud:

http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true

system_health:

system_log:

logger:
  default: warn
  # logs:
  #   custom_components.hacs: debug

hassio:

discovery:

recorder:
  db_url: !secret database_url
  purge_interval: 1
  purge_keep_days: 60

history:

logbook:

sun:

sensor: !include_dir_list sensors

binary_sensor: !include_dir_list binary_sensors

cover:
  - platform: myq
    username: !secret liftmaster_username
    password: !secret liftmaster_password
    type: liftmaster

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 300

zwave:
  usb_path: !secret zwave_mount
  network_key: !secret zwave_network_key
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml

media_player: !include media_players.yaml

unifi:
  controllers:
    - site: !secret unifi_site
      host: !secret unifi_host
      detection_time: 300

notify:
  - name: webapp
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

group: !include_dir_named groups
scene: !include scenes.yaml
automation: !include_dir_list automations
script: !include_dir_named scripts

input_boolean: !include input_booleans.yaml

envisalink: !include envisalink.yaml

rest_command: !include_dir_named rest_commands

owntracks:
  max_gps_accuracy: 150
  secret: !secret owntracks_key

auto_backup:
  auto_purge: true
