homeassistant:
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml

default_config:

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

logger:
  default: warn

hassio:

recorder:
  db_url: !secret database_url
  purge_keep_days: 60

group: !include_dir_named groups

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 300

notify:
  - name: webapp
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

alert: !include_dir_named alerts

envisalink: !include envisalink.yaml
