homeassistant:
  name: Feliciterra
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml

zone: !include zones.yaml

frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

config:

cloud:

http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  include_used_components: true

system_health:

system_log:

hassio:

discovery:

recorder:
  db_url: !secret database_url
  purge_interval: 1
  purge_keep_days: 60

history:

logbook:

sun:

sensor:
  # https://www.home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: memory_free

cover:
  - platform: myq
    username: !secret liftmaster_username
    password: !secret liftmaster_password
    type: liftmaster

tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 300

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml

media_player: !include media_players.yaml

unifi:
  controllers:
    - site: !secret unifi_site
      host: !secret unifi_host
      detection_time: 300

notify:
  - name: webapp
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_boolean: !include input_booleans.yaml

envisalink:
  host: !secret envisalink_host
  panel_type: DSC
  user_name: !secret envisalink_user
  password: !secret envisalink_password
  code: !secret envisalink_code
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30
  timeout: 10
  panic_type: Police
  zones:
    1:
      name: 'Front door'
      type: 'opening'
    2:
      name: 'Pool bathroom door'
      type: 'opening'
    3:
      name: 'Back door'
      type: 'opening'
    4:
      name: 'Great room glass break'
      type: 'sound'
    5:
      name: 'Guest room glass break'
      type: 'sound'
    6:
      name: 'Office glass break'
      type: 'sound'
    7:
      name: 'Library glass break'
      type: 'sound'
    8:
      name: 'Master bedroom glass break'
    17:
      name: 'Garage door'
      type: 'opening'
  partitions:
    1:
      name: 'Home Alarm'
