homeassistant:
  # Name of the location where Home Assistant is running
  name: Feliciterra
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret home_time_zone
  # Customization file
  # customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  customize_domain: !include customize_domain.yaml

zone: !include zones.yaml

# Enables the frontend
frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml

# Enables configuration UI
config:

# Enables home assistant cloud
cloud:

http:
  base_url: !secret http_base_url
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

system_health:

system_log:

hassio:

discovery:

recorder:
  db_url: !secret database_url
  purge_interval: 1
  purge_keep_days: 60

history:

logbook:

sun:

sensor:
  # https://www.home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: memory_use_percent
      - type: memory_free

cover:
  - platform: myq
    username: !secret liftmaster_username
    password: !secret liftmaster_password
    type: liftmaster

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    time_memory: 300

vera:
  vera_controller_url: !secret vera_controller_url

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml

# TODO: fix usps integration, it's unstable
# usps:
#   username: !secret usps_username
#   password: !secret usps_password

media_player: !include media_players.yaml

unifi:
  controllers:
    - site: !secret unifi_site
      host: !secret unifi_host
      port: 443
      username: !secret unifi_username
      password: !secret unifi_password
      detection_time: 300

notify:
  - name: webapp
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
rest_command: !include rest_commands.yaml

input_boolean: !include input_booleans.yaml
