title: Home
views:
  - !include views/home.yaml
  - !include views/switches.yaml
  - !include views/everything-else.yaml
  - !include views/zwave-network.yaml
  - !include views/system.yaml

resources:
  - url: /community_plugin/monster-card/monster-card.js
    type: js
