alias: Polaris on
trigger:
  - platform: sun
    event: sunset
    offset: '-01:00:00'
  - platform: sun
    event: sunrise
action:
  - service: homeassistant.turn_on
    entity_id: switch.pool_doggy
  - delay: 3600
  - service: homeassistant.turn_off
    entity_id: switch.pool_doggy

