alias: Right garage door timeout
trigger:
  platform: state
  entity_id: cover.garage_door_right
  to: open
  for:
    minutes: 10
condition:
  condition: state
  entity_id: input_boolean.door_timeouts
  state: 'on'
action:
  - service: cover.close_cover
    entity_id: cover.garage_door_right
