alias: Arriving
trigger:
  platform: state
  entity_id:
    - person.brooke_turney
    - person.matthew_turney
  from: not_home
  to: home
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.away
