alias: Evening while away
trigger:
  platform: time
  at: '21:45:00'
condition:
  condition: state
  entity_id: input_boolean.away
  state: 'on'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.asleep
