alias: Leaving
trigger:
  platform: state
  entity_id:
    - person.brooke_turney
    - person.matthew_turney
    - device_tracker.milton_phone
    # - device_tracker.esther_phone
    - device_tracker.kacki_phone
    - device_tracker.dally_phone
    - device_tracker.housekeeper_phone
  from: home
  to: not_home
  # Delayed action for network devices to prevent false positives.
  for:
    minutes: 2
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
    - condition: state
      entity_id: person.brooke_turney
      state: not_home
    - condition: state
      entity_id: person.matthew_turney
      state: not_home
    - condition: state
      entity_id: device_tracker.milton_phone
      state: not_home
    # - condition: state
    #   entity_id: device_tracker.esther_phone
    #   state: not_home
    - condition: state
      entity_id: device_tracker.kacki_phone
      state: not_home
    - condition: state
      entity_id: device_tracker.dally_phone
      state: not_home
    - condition: state
      entity_id: device_tracker.housekeeper_phone
      state: not_home
action:
  service: input_boolean.turn_on
  entity_id: input_boolean.away
