alias: Leaving
trigger:
  platform: state
  entity_id:
    - person.brooke_turney
    - person.matthew_turney
    - person.dally
    - person.kacky
    - person.esther_turney
    - person.milton_turney
  from: home
  to: not_home
  # Delayed action for network devices to prevent false positives.
  for:
    minutes: 2
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.away
      state: 'off'
    - condition: state
      entity_id:
        - person.brooke_turney
        - person.matthew_turney
        - person.dally
        - person.kacky
        - person.esther_turney
        - person.milton_turney
      state:
        - not_home
        - unknown
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.away
