alias: Driveway alarm
trigger:
  platform: state
  entity_id: sensor.front_detected_object
  to: 'vehicle'
action:
  - service: tts.cloud_say
    data:
      entity_id:
        - media_player.pool_speaker
        - media_player.driveway_alarm
      message: Vehicle in driveway
