alias: Away on
trigger:
  platform: state
  entity_id: input_boolean.away
  to: 'on'
action:
  - service: alarm_control_panel.alarm_arm_away
  - service: lock.lock
    entity_id:
      - lock.garage_door
      - lock.front_door
  - service: homeassistant.turn_off
    entity_id:
      - media_player.vizio_smartcast
      - switch.mudroom_hallway_lights
      - switch.foyer_outlet
      - switch.great_room_back_wall
      - switch.great_room_center_lights
      - switch.kitchen_cabinet_lights
  - service: cover.close_cover
    entity_id:
      - cover.garage_door_left
      - cover.garage_door_right
