alias: Away on
trigger:
  platform: state
  entity_id: input_boolean.away
  to: 'on'
action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.home_alarm
  - service: lock.lock
    entity_id:
      - lock.garage_door
      - lock.front_door
  - service: homeassistant.turn_off
    entity_id:
      - media_player.great_room_tv
      - light.great_room_lamp
      - light.library_lights
      - switch.mudroom_hallway_lights
      - switch.foyer_outlet
      - switch.great_room_back_wall
      - light.great_room_center_lights
      - switch.kitchen_pantry_lights
      - switch.kitchen_cabinet_lights
  - service: cover.close_cover
    entity_id:
      - cover.left_garage_door
      - cover.right_garage_door
  - condition: state
    entity_id: input_boolean.christmas_time
    state: 'on'
  - service: switch.turn_off
    entity_id: group.indoor_christmas_lights
