alias: Evening
trigger:
  platform: time
  at: '16:45:00'
condition:
  condition: state
  entity_id: input_boolean.away
  state: 'off'
action:
  - service: homeassistant.turn_on
    entity_id:
      - switch.kitchen_cabinet_lights
      - switch.kitchen_pantry_lights
      - switch.library_outlet
