alias: Notify pool bathroom door open
trigger:
  platform: state
  entity_id: binary_sensor.pool_bathroom_door
  to: 'on'
  for:
    minutes: 3
action:
  - service: notify.webapp
    data:
      title: Pool bathroom door
      message:
        Pool bathroom door is open, you should go close it. Be sure to check for
        the pets and children.
      data:
        tag: pool-bathroom-door-notification
