alias: Smoke detected
trigger:
  platform: state
  entity_id: binary_sensor.fire_detectors
  to: 'on'
action:
  - service: notify.webapp
    data:
      title: Smoke detected
      data:
        tag: smoke-detected-notification
