alias: Home Assistant backup
trigger:
  platform: time
  at: '1:00:00'
action:
- service: auto_backup.snapshot_full
  data_template:
    name: "daily-backup--{{ now().isoformat(timespec='minutes') }}"
    keep_days: 7
