alias: Home Assistant backup failed
trigger:
  platform: event
  event_type: auto_backup.backup_failed
action:
  - service: notify.webapp
    data_template:
      title: Backup failed
      message: |
        Configuration backup failed for {{trigger.event.data.name}}.
        Error: {{ trigger.event.data.error }}
      data:
        tag: hass-backup-failed-notification
